#!/usr/bin/env python3
"""Sync Gemini Web cookies from the local desktop browser into data/runtime.env.

The proxy running in a Docker container cannot read Safari/Chrome cookies on
macOS.  This script runs on the host, reads the cookies via
``browser-cookie3``, and writes a ``GOP_GEMINI_1PSID``/``GOP_GEMINI_1PSIDTS``
pair (plus ``GOP_HTTP_PROXY``) into ``data/runtime.env`` so the container
can authenticate without touching the browser.

Usage:
    python scripts/sync_runtime_env.py [--browser safari] [--out data/runtime.env]
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
# Prefer the installed package, fall back to the src/ layout (editable-less).
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if SRC.is_dir() and str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

# Touch the package to trigger cookie-source registration.
from gemini_webapi_proxy import cookies as _cookies  # noqa: E402,F401
from gemini_webapi_proxy.cookies import SOURCES, build_source  # noqa: E402


def _escape_env(value: str) -> str:
    if not value:
        return '""'
    if any(ch in value for ch in " \t#\"'"):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


async def _read_from_browser(browser: str) -> tuple[str, str, dict[str, str]]:
    bundle = await build_source("browser", browser=browser).load()
    return bundle.psid, bundle.psidts, dict(bundle.extras)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--browser",
        default=os.getenv("BROWSER_COOKIE", "safari").strip().lower() or "safari",
        help="Preferred browser (safari/chrome/edge/brave/chromium)",
    )
    p.add_argument(
        "--out",
        type=Path,
        default=ROOT / "data" / "runtime.env",
        help="Output env file (default: data/runtime.env)",
    )
    p.add_argument(
        "--docker-proxy",
        default=os.getenv("DOCKER_HTTP_PROXY", "http://host.docker.internal:7897").strip(),
    )
    args = p.parse_args()

    if "browser" not in SOURCES:
        print("browser-cookie source unavailable; install browser-cookie3", file=sys.stderr)
        return 2

    try:
        psid, psidts, extras = asyncio.run(_read_from_browser(args.browser))
    except Exception as exc:
        print(f"Failed to read browser cookies: {exc}", file=sys.stderr)
        return 1

    if not psid:
        print("No __Secure-1PSID found; log in to gemini.google.com first.", file=sys.stderr)
        return 1

    # Extras are written as `k=v; k=v` so the env source can merge them back
    # into CookieBundle.extras.  PSID/PSIDTS are NOT repeated in the raw blob
    # to avoid double-counting.
    extras_blob = "; ".join(
        f"{name}={value}"
        for name, value in extras.items()
        if name not in {"__Secure-1PSID", "__Secure-1PSIDTS"}
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by scripts/sync_runtime_env.py — do NOT commit",
        "GOP_COOKIE_SOURCE=env",
        f"GOP_GEMINI_1PSID={_escape_env(psid)}",
        f"GOP_GEMINI_1PSIDTS={_escape_env(psidts)}",
        f"GOP_GEMINI_COOKIES_RAW={_escape_env(extras_blob)}",
        f"GOP_HTTP_PROXY={_escape_env(args.docker_proxy)}",
        "GOP_PROBE_ON_START=false",
        "GOP_PORT=4982",
    ]
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        args.out.chmod(0o600)
    except OSError:
        pass

    print(f"Wrote {args.out} (browser: {args.browser})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
