"""Unit tests for the model registry (alias resolution, kind inference)."""

from __future__ import annotations

from gemini_openai_proxy.client.base import ModelDescriptor
from gemini_openai_proxy.client.registry import ModelRegistry, _guess_kind


def test_guess_kind_image() -> None:
    assert _guess_kind("gemini-2.5-flash-image", "") == "image"
    assert _guess_kind("gemini-3-pro", "Image generation") == "image"


def test_guess_kind_tts_is_chat() -> None:
    assert _guess_kind("gemini-tts", "text to speech") == "chat"
    assert _guess_kind("music-generator", "") == "chat"


def test_guess_kind_thinking_is_chat() -> None:
    assert _guess_kind("gemini-thinking", "deep reasoning") == "chat"


def test_guess_kind_default_is_chat() -> None:
    assert _guess_kind("gemini-3-flash", "fast help") == "chat"


def test_registry_resolve_exact_match() -> None:
    r = ModelRegistry()
    r.sync_from_client(
        [
            _mk("gemini-3-flash", "fast", "lightning"),
            _mk("gemini-3-pro", "deep", "advanced"),
        ]
    )
    assert r.resolve_id("gemini-3-flash") == "gemini-3-flash"
    assert r.resolve_id("gemini-3-pro") == "gemini-3-pro"


def test_registry_resolve_alias() -> None:
    r = ModelRegistry()
    r.sync_from_client([_mk("gemini-3-pro", "Pro", "high")])
    # Aliases auto-generated by sync_from_client
    assert r.resolve_id("gemini-3-pro-preview") == "gemini-3-pro"


def test_registry_pick_image_prefers_probed() -> None:
    r = ModelRegistry()
    r.sync_from_client(
        [
            _mk("gemini-3-flash", "fast", "chat"),
            _mk("gemini-3-pro-image-preview", "image", "image gen"),
        ]
    )
    r.update_probe("gemini-3-pro-image-preview", image_ok=True)
    r.update_probe("gemini-3-flash", chat_ok=True)
    assert r.pick_image_model() == "gemini-3-pro-image-preview"


def test_registry_pick_image_falls_back_to_kind() -> None:
    r = ModelRegistry()
    r.sync_from_client([_mk("gemini-3-flash", "fast", "chat")])
    r.update_probe("gemini-3-flash", chat_ok=True)
    # No image model probed; should still return a usable id
    picked = r.pick_image_model()
    assert picked == "gemini-3-flash"


def test_registry_list_openai_includes_aliases() -> None:
    r = ModelRegistry()
    r.sync_from_client([_mk("gemini-3-pro", "Pro", "high")])
    items = r.list_openai_models()
    ids = {item["id"] for item in items}
    assert "gemini-3-pro" in ids
    # The alias was added by sync_from_client
    assert any(i.startswith("gemini-3-pro") for i in ids)


def _mk(name: str, display: str, desc: str) -> ModelDescriptor:
    return ModelDescriptor(name=name, display_name=display, description=desc)
